Controllers/CarrinhoDeCompraController.cs
using System.Linq;
using LanchesMac.Models;
using LanchesMac.Reposiitories;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class CarrinhoDeCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoDeCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;

            
        }


        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraViewModel = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraViewModel);
        }
        [Authorize]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(
                p => p.LancheId == lancheId);

            if(lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarCarrinho(lancheSelecionado, 1);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public RedirectToActionResult RemoverItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(
                p => p.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoveDoCariinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/ContatoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class ContatoController : Controller
    {

        public IActionResult Index()
        {
            //if (User.Identity.IsAuthenticated)
            //{
                return View();
            //}
            //return RedirectToAction("Login","Account");
        }
    }
}

Controllers/LancheController.cs
using LancheMac.Models;
using LanchesMac.Reposiitories;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller

    {
        private readonly ILancheRepository _lancheRespository;
         private readonly ICategoriaRepository _categoriaRepository;
        public LancheController(ILancheRepository lacheRepository, ICategoriaRepository categoriaRepository)
        {
            _lancheRespository = lacheRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult List(string categoria)

        {
            string _categoria = categoria;
            IEnumerable<Lanche> lanches;
            
            string categoriaAtual = string.Empty;
            
            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRespository.Lanches.OrderBy(l => l.LancheId);
                categoria = "Todos os Lanches";
            }
            else
            {
                if(string.Equals("Lanche Natural", _categoria, StringComparison.OrdinalIgnoreCase))
                {
                    lanches = _lancheRespository.Lanches.Where(l => l.Categoria.CategoriaId.Equals(1))
                        .OrderBy(l => l.Nome);
                }
                else
                {
                    lanches = _lancheRespository.Lanches.Where(l => l.Categoria.CategoriaId.Equals(2))
                      .OrderBy(l => l.Nome);
                }
                categoriaAtual = _categoria;
            }


            var lanchelistViewModel = new LancheListViewModel()
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };
          
            return View(lanchelistViewModel);
        }

        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRespository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);

            if (lanche == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }

            return View(lanche);
        }

        public IActionResult Search(string searchString)
        {
            String _searchString = searchString;
            IEnumerable<Lanche> lanches;

            if (string.IsNullOrEmpty(_searchString))
            {
                lanches = _lancheRespository.Lanches.OrderBy(l => l.LancheId);
            }
            else
            {
                lanches = _lancheRespository.Lanches.Where(l => l.Nome.ToLower().Contains(_searchString.ToLower())) ;
            }

            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel {Lanches = lanches, CategoriaAtual="Todos os lanches" });
        }


    }
}

Views/Shared/_Carousel.cshtml
<div class="row carousel-holder marginTop1">
    <div class="col-md-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
                <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner">
                <div class="item active">
                    <img class="slide-image" src="~/Images/carousel11.jpg" alt="" width="1000" height="500">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel12.jpg" alt="" width="1000" height="500">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel13.jpg" alt="" width="1000" height="500">
                </div>
                <div class="item">
                    <img class="slide-image" src="~/Images/carousel14.jpg" alt="" width="1000" height="500">
                </div>
            </div>
            <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                <span class="glyphicon glyphicon-chevron-left"></span>
            </a>
            <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                <span class="glyphicon glyphicon-chevron-right"></span>
            </a>
        </div>
    </div>
</div>

Views/Shared/_LanchesResumo.cshtml
@model LancheMac.Models.Lanche

<div class="col-sm-4 col-lg-4 col-md-4">
    <div class="thumbnail">
        <img src="@Model.imagemUrl" class="img-rounded" alt="@Model.Nome" width="225" height="225" />
        <div class="caption">
            <h3 class="pull-right">@Model.Preco.ToString("c")</h3>
            <h3>
                <a asp-controller="Lanche" asp-action="Details" asp-route-lancheId="@Model.LancheId">@Model.Nome</a>
            </h3>
            <p>@Model.DescricaoCurta</p>
        </div>
        <div class="addToCart text-right">
            <p class="button ">
                <a class="btn btn-primary" id="cartButton" asp-controller="CarrinhoDeCompra" asp-action="AdicionarItemNoCarrinhoCompra" asp-route-lancheId="@Model.LancheId">
                    Incluir no Carrinho
                </a>
            </p>
        </div>
    </div>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - LanchesMac</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">LanchesMac</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @await Component.InvokeAsync("CategoriaMenu")
                    <li><a asp-area="" asp-controller="Contato" asp-action="Index">Contato</a></li>
                   
                    @if (User.IsInRole("Admin"))
                    {
                        <li><a asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a></li>
                    }
                    @if (User.Identity.IsAuthenticated)
                    {
                        @await Component.InvokeAsync("CarrinhoCompraResumo")
                    }
                </ul>
                @await Html.PartialAsync("_LoginPartial");
                <form class="navbar-form navbar-right" asp-controller="Lanche" asp-action="Search" method="get">
                    <div class="form-group">
                        <input type="text" class="form-control" placeholder="Procurar lanche" name="searchString" value="@ViewData["searchString"]">
                    </div>
                </form>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - LanchesMac</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_LnachesResumo.cshtml
     <div class="col-sm-4 colo-lg-4 col-md-4">
        <div class="thumbnail">
            <p><img src="@Model.imagemUrl" class="img-rounded" /></p>
        </div>
        <div class="caption">
            <h3 class="pull-right">
                @Model.Preco.ToString("c")
            </h3>
            <p>@Model.DescricaoCurta</p>
        </div>

    </div>