Controllers/CarrinhoDeCompraController.cs
using System.Linq;
using LanchesMac.Models;
using LanchesMac.Reposiitories;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class CarrinhoDeCompraController : Controller
    {
        private readonly ILancheRepository _lancheRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoDeCompraController(ILancheRepository lancheRepository, CarrinhoCompra carrinhoCompra)
        {
            _lancheRepository = lancheRepository;
            _carrinhoCompra = carrinhoCompra;

            
        }


        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;

            var carrinhoCompraViewModel = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };

            return View(carrinhoCompraViewModel);
        }
        [Authorize]
        public RedirectToActionResult AdicionarItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(
                p => p.LancheId == lancheId);

            if(lancheSelecionado != null)
            {
                _carrinhoCompra.AdicionarCarrinho(lancheSelecionado, 1);
            }

            return RedirectToAction("Index");
        }

        [Authorize]
        public RedirectToActionResult RemoverItemNoCarrinhoCompra(int lancheId)
        {
            var lancheSelecionado = _lancheRepository.Lanches.FirstOrDefault(
                p => p.LancheId == lancheId);

            if (lancheSelecionado != null)
            {
                _carrinhoCompra.RemoveDoCariinho(lancheSelecionado);
            }

            return RedirectToAction("Index");
        }
    }
}

Controllers/LancheController.cs
using LancheMac.Models;
using LanchesMac.Reposiitories;
using LanchesMac.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;

namespace LanchesMac.Controllers
{
    public class LancheController : Controller

    {
        private readonly ILancheRepository _lancheRespository;
         private readonly ICategoriaRepository _categoriaRepository;
        public LancheController(ILancheRepository lacheRepository, ICategoriaRepository categoriaRepository)
        {
            _lancheRespository = lacheRepository;
            _categoriaRepository = categoriaRepository;
        }

        public IActionResult List(string categoria)

        {
            string _categoria = categoria;
            IEnumerable<Lanche> lanches;
            
            string categoriaAtual = string.Empty;
            
            if (string.IsNullOrEmpty(categoria))
            {
                lanches = _lancheRespository.Lanches.OrderBy(l => l.LancheId);
                categoria = "Todos os Lanches";
            }
            else
            {
                if(string.Equals("Lanche Natural", _categoria, StringComparison.OrdinalIgnoreCase))
                {
                    lanches = _lancheRespository.Lanches.Where(l => l.Categoria.CategoriaId.Equals(1))
                        .OrderBy(l => l.Nome);
                }
                else
                {
                    lanches = _lancheRespository.Lanches.Where(l => l.Categoria.CategoriaId.Equals(2))
                      .OrderBy(l => l.Nome);
                }
                categoriaAtual = _categoria;
            }


            var lanchelistViewModel = new LancheListViewModel()
            {
                Lanches = lanches,
                CategoriaAtual = categoriaAtual
            };
          
            return View(lanchelistViewModel);
        }

        public IActionResult Details(int lancheId)
        {
            var lanche = _lancheRespository.Lanches.FirstOrDefault(l => l.LancheId == lancheId);

            if (lanche == null)
            {
                return View("~/Views/Error/Error.cshtml");
            }

            return View(lanche);
        }

        public IActionResult Search(string searchString)
        {
            String _searchString = searchString;
            IEnumerable<Lanche> lanches;

            if (string.IsNullOrEmpty(_searchString))
            {
                lanches = _lancheRespository.Lanches.OrderBy(l => l.LancheId);
            }
            else
            {
                lanches = _lancheRespository.Lanches.Where(l => l.Nome.ToLower().Contains(_searchString.ToLower())) ;
            }

            return View("~/Views/Lanche/List.cshtml", new LancheListViewModel {Lanches = lanches, CategoriaAtual="Todos os lanches" });
        }


    }
}

Controllers/PedidoController.cs
using LanchesMac.Models;
using LanchesMac.Reposiitories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace LanchesMac.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public PedidoController(IPedidoRepository pedidoRepository, CarrinhoCompra carrinhoCompra)
        {
            _pedidoRepository = pedidoRepository;
            _carrinhoCompra = carrinhoCompra;
        }
        [Authorize]
        [HttpGet]
        public IActionResult Checkout()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItens = itens;
            if (_carrinhoCompra.CarrinhoCompraItens.Count == 0)
            {
                ModelState.AddModelError("", "Seu carrinho está vazio inclua um lanche...");
            }

            if (ModelState.IsValid)
            {
                _pedidoRepository.CriarPedido(pedido);
                _carrinhoCompra.LimparCarrinho();
                return RedirectToAction("CheckoutCompleto");
            }
            return View(pedido);
        }

        public IActionResult CheckoutCompleto()
        {
            ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido :) ";
            return View();
        }
    }
}

Views/CarrinhoDeCompra/Index.cshtml
@model CarrinhoCompraViewModel

<div class="row checkoutForm">
    <h2>Seu carrinho de compras</h2>
    <h4>Aqui estão os seus pedidos</h4>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Quantidade</th>
                <th>Lanche</th>
                <th class="text-right">Preço</th>
                <th class="text-right">Subtotal</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.CarrinhoCompra.CarrinhoCompraItens)
            {
                <tr>
                    <td class="text-center">@item.Quantidade</td>
                    <td class="text-left">@item.Lanche.Nome</td>
                    <td class="text-right">@item.Lanche.Preco.ToString("c")</td>
                    <td class="text-right">
                        @((item.Quantidade * item.Lanche.Preco).ToString("c"))
                    </td>
                    <td class="text-center"><a class="glyphicon glyphicon-remove text-danger remove" asp-controller="CarrinhoCompra" asp-action="RemoverItemDoCarrinhoCompra" asp-route-lancheId="@item.Lanche.LancheId"></a></td>
                </tr>
            }
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" class="text-right">Total:</td>
                <td class="text-right">
                    @Model.CarrinhoCompraTotal.ToString("c")
                </td>
            </tr>
        </tfoot>
    </table>

    <div class="text-right">
        <div class="btn-group ">
            <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar Pedido</a>
            <a class="btn-group">
                <a class="btn btn-default dropdown-toggle" data-toggle="dropdown">
                    Adicionar mais lanches<span class="caret"></span>
                </a>
                <ul class="dropdown-menu" role="menu">
                    <li><a asp-controller="Lanche" asp-action="List" asp-route-categoria="Normal">Normal</a></li>
                    <li><a asp-controller="Lanche" asp-action="List" asp-route-categoria="Natural">Natural</a></li>
                </ul>
            </a>
        </div>
    </div>
</div>